version: '3.4'

services:
  #mars-rover.webapp:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mars-rover.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=marsrover.db;Database=marsroverdb;User Id=useryasin;password=marsroverpassword
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
